baseURL = "https://dunamismax.com/"
languageCode = "en-us"
title = "dunamismax blog"
theme = "mytheme"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
