baseURL = "https://dunamismax.com/"
languageCode = "en-us"
title = "dunamismax blog"

[module]
  [[module.imports]]
    path = "github.com/hugo-sid/hugo-blog-awesome"

    [menu]
      [[menu.main]]
        name = "Home"
        url = "/"
        weight = 1
      [[menu.main]]
        name = "Blog"
        url = "/posts/"
        weight = 2