baseURL = "https://dunamismax.com/"
languageCode = "en-us"
title = "dunamismax blog"
theme = "mytheme"

[params]
  [params.author]
    name = "Dunamismax"
    intro = "Hello, I'm DunamisMax!"
    description = "I'm an IT Professional who writes about tech, Go, and self-hosting."

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/dunamismax"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/dunamismax"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
