baseURL = 'https://dunamismax.com/'
languageCode = 'en-us'
title = 'dunamismax.com'
theme = "hugo-paper"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2
