baseURL = 'https://dunamismax.com/'
languageCode = 'en-us'
title = 'dunamismax.com'
theme = 'hugo-paper'

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 2

[params]
  # color style options: linen, wheat, gray, light
  color = 'linen'

  # Social & identity
  name = 'DunamisMax'
  bio = 'IT Director learning software engineering with Go'

  # Social links
  github = 'DunamisMax'                      # github.com/DunamisMax
  bluesky = 'dunamismax.bsky.social'         # https://bsky.app/profile/dunamismax.bsky.social

  # Home page avatar
  avatar = '/images/avatar.png'

  # Misc settings
  disablePostNavigation = true
  monoDarkIcon = true
  math = true                # enable KaTeX math typesetting globally
  localKatex = false
  favicon = '/images/favicon.ico'